### ISSUE TITLE
Styles for React Native

### ISSUE THREAD

**Issue by raphaelspimenta** [ZupIT/beagle-web-react#132]
**What would you like to be added**:
Currently, our process of converting the backend styles to CSS styles is focused on the web environment. We need to change it in order to work correctly for React Native too. For example, in RN, images don't accept sizes in `px`.

**Why is this needed**:
Not every style processed from BFF works in React Native.

**Comment by hectorcustodiozup** [comment]
It was already added with the PR https://github.com/ZupIT/beagle-web-react/pull/145. Beagle lifecycle method was used to solve this problem.
