### ISSUE TITLE
Styled-components dependency error

### ISSUE THREAD

**Issue by lbittencurt** [ZupIT/beagle-web-react#146]
Beagle React version:

## Problem
The guide to start a project with React don't provide a suggestion to install styled-components. The developer needs to find the error and install the dependency to fix.

## Steps To Reproduce

1. Follow the Beagle React guide instructions (https://docs.usebeagle.io/get-started/new-project/case-web)

Error: 
![image](https://user-images.githubusercontent.com/65682607/93260779-383ed700-f778-11ea-91ee-784cdac8618a.png)

**Comment by Tiagoperes** [comment]
Thanks for letting us know! We are working to completely remove the dependency, but while it's not completed, we'll check what's  wrong in our package.json regarding the styled-components.
