### ISSUE TITLE
Change the default error component to take advantage of new properties (React-WEB)

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-react#150]
We now have properties that are passed to the ErrorComponent. Our default ErrorComponent should take advantage of this by using both the retry function and the array of errors.

**Comment by rafaeelaudibert** [comment]
Hello @Tiagoperes! May you assign this to me? I'd be interested in doing this. I understand what should be done with the `errors `array, but what should I do with the `retry `function?

**Comment by Tiagoperes** [comment]
Hello @rafaeelaudibert , I'm very sorry that I missed you commentary. I really didn't see it and found it out just now because I was specifically looking for this issue.

If you still want to contribute, here's the answer for your question:

The component BeagleError receives following props:
- className: the styling class to apply;
- errors: array with all errors that caused this component to appear;
- retry: a function that, when called, will retry the operation that caused this error component to appear. For instance, it it was a request that failed because the internet connection was unavailable, the request will be retried.

For the array of errors, we can print the errors to the screen, below the text "An unexpected error happened while loading your page.".

For the `retry` function, we must create a button written `retry` that, when clicked, calls the function "retry".
