### ISSUE TITLE
React 17 compatibility

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-react#169]
It looks like Beagle is not compatible with the new React 17. We should check and fix it if it's broken.

**Comment by gabrielmiranda-ctrl** [comment]
I did the test with all the components separated and together. No errors were found, so nothing should be done

**Comment by Tiagoperes** [comment]
Since we previously had an issue where it worked on Windows but not on Mac, I also tested this for Mac.

Just like in Gabriel's test, it also worked. So I'm closing this issue.
