### ISSUE TITLE
Modal component behind other components

### ISSUE THREAD

**Issue by gabrielmiranda-ctrl** [ZupIT/beagle-web-react#190]
The Modal component is behind the Page View and Tab Bar components

I believe that the ideal is the modal to be apparent in any situation

![Capturar](https://user-images.githubusercontent.com/59086970/114717737-ba41af00-9d0b-11eb-8ec9-293dc9e188bb.PNG)
![Capturar2](https://user-images.githubusercontent.com/59086970/114717741-bada4580-9d0b-11eb-8ac1-c85338e470e6.PNG)

**Comment by Tiagoperes** [comment]
Nice! Can you. check for us if it also happens in Angular? Are you going to fix this? If, yes, please assign this issue to yourself.
