### ISSUE TITLE
Not able to run React web project using basic Beagle seetings given in the document

### ISSUE THREAD

**Issue by nitinjainhcl** [ZupIT/beagle-web-react#221]
Beagle React version: 1.10

## Steps To Reproduce

1. npm install --save @zup-it/beagle-react
2. JSON creation - payload.json
3. create beagle-service.ts
4. Modify app.js

Followed all the steps given https://www.npmjs.com/package/@zup-it/beagle-react to install Begale React in new REact web proejct, facing JSON issue - "ERROR: Unexpected token < in JSON at position 0"

![image](https://user-images.githubusercontent.com/90447296/136216466-07c1bfc3-deb6-4b17-a8bc-22a9681ed58f.png)

what i also found is when i open the network tab and look for payload.json i found 

![image](https://user-images.githubusercontent.com/90447296/136216893-ea2f59d4-9b8a-4896-83b8-9cb5d54f36ed.png)

Link to code example:

**Comment by Tiagoperes** [comment]
The application is not serving your `payload.json` file. Probably a configuration in webpack.

In any case, you'll use a real backend and not local files. You can skip this silly example.

In your Beagle Configuration you can specify the following `baseUrl`: "http://usebeagle.io.s3-website-sa-east-1.amazonaws.com/start".

```typescript
import { createBeagleUIService } from '@zup-it/beagle-react'

export default createBeagleUIService({
  baseUrl: "http://usebeagle.io.s3-website-sa-east-1.amazonaws.com/start",
  components: {}
})
```

And for the view will load, you must use `/welcome`:

```typescript
function App() {
  return (
    <BeagleProvider value={BeagleService}>
      <BeagleRemoteView path={'/welcome'} />
    </BeagleProvider>
  );
}
```

This will render a sample welcome page, just for you to see it's working. For real projects, you need a backend to serve your JSONs and the url for the backend should be provided in `baseUrl`.

The backend can be created using any tool, as long as it produces valid Beagle JSONs. To make it easier, we have a Backend Framework in Kotlin. If this interests you, please check the documentation [here](https://docs.usebeagle.io/v1.10/backend/get-started/installing-beagle/).
