### ISSUE TITLE
Reexportar loadParams 

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-react#96]
**What would you like to be added**:
Reexportar loadParams que está definido no core para que o usuário final possa importar da lib que ele mesmo instalou, no caso beagle-react, ao invés de importar do web que ele não instalou diretamente.

**Why is this needed**:
Evitar confusões para o usuário final na hora de usar

**Comment by Tiagoperes** [comment]
loadParams foi depreciado.
Reexportar o ActionHandler cria precedente para reexportarmos qualquer coisa do `@zup=it/beagle-web`, não acho que seja boa ideia.
